### ISSUE TITLE
Example is too barebones to help me decide whether I should use this library.

### ISSUE THREAD

**Issue by rattrayalex** [aehrenthal/openapi-to-ts#12]
It's really helpful to link to an example from the readme (thank you!) but unfortunately it's too minimal to tell me much. [This package](https://www.npmjs.com/package/openapi-typescript) links to an example from Stripe, which is quite full-featured and makes it easy to see what things might look like in practice.

Would you consider doing the same thing?

**Comment by aehrenthal** [comment]
Hello @rattrayalex, I apologize for my late reply - I was traveling on a longer vacation and just finally got back to work. I just extended the examples folder, so that now we have a simple and an advanced example. I hope this is what you were looking for.

**Comment by rattrayalex** [comment]
Amazing, thank you! Hope you had an amazing vacation :-) gearing up for a big one myself…

**Comment by aehrenthal** [comment]
Thanks a lot, after such a long time it was a real pleasure to travel again to see family and friends. I hope you will have a great time on your vacation too! 😊  Feel free to let me know if I can do anything else to assist you with your choice between this library or any other projects.

**Comment by rattrayalex** [comment]
Thank you!
This looks like a very helpful example… to be honest, I think it may expose some bugs! 

`Partial` seems to be applied a bit too often… and it looks like it is not generating types for params/bodies? or am I just missing something? Regardless, these are doubtless separate issues, and I will let you take a look through to see what you think is right to address in this library!

This definitely gives the information I need (not right for my project right now) so this issue is closed with satisfaction!
