### ISSUE TITLE
Would you be interested in combining repos?

### ISSUE THREAD

**Issue by drwpow** [aehrenthal/openapi-to-ts#6]
👋🏻  Hello! I’m the author of [swagger-to-ts](https://github.com/drwpow/swagger-to-ts), a [related package](https://www.npmjs.com/package/@manifoldco/swagger-to-ts) with 20+ contributors and some regular downloaders/users. Due to a job change, I have to change the package name ([discussion](https://github.com/drwpow/swagger-to-ts/issues/332)).

Seeing as the projects seem similar in scope and name, would you be interested in combining projects/code and publishing both under the `openapi-to-ts` npm name? Feel free to say “no;” just thought this could be an opportunity to reduce a number of similar packages.

**Differences**

On a first glance, I think the biggest difference between the 2 packages is the end generation. This package returns neat `PascalCase` names. While I did that on v1, I eventually had to abandon that for v2 and allow `Illegal.JavaScript-Characters` like the OpenAPI schema allows. But in exchange for that, we can generate TypeScript types for some really complicated schemas like [Stripe’s](https://github.com/drwpow/swagger-to-ts/blob/master/tests/v3/specs/stripe.yaml) and [GitHub’s](https://github.com/drwpow/swagger-to-ts/blob/master/tests/v3/specs/github.yaml).

**Similiarities**

Obviously the goal of the project is to turn OpenAPI 3 -> TypeScript schemas, and in that regard I think the projects are more similar than different. swagger-to-ts also handles OpenAPI 2 as well.

**Combining**

What would combining look like? To be honest, I’m not too particular about any of the code in swagger-to-ts; it could all be refactored for all I care (and it has been several times!). I more just care that:

- The extensive [test suite](https://github.com/drwpow/swagger-to-ts/blob/master/tests/v3/specs/github.yaml) is kept
- [Really complicated schemas](https://github.com/drwpow/swagger-to-ts/tree/master/tests/v3/specs) (more complicated than the Petstore example) can be generated (including ones that contain illegal JS characters)
- Performance is fast enough that `npx` can run it no problem.

If you agree with that approach, then I’m open to whatever moving forward looks like, even repo ownership. I just saw an opportunity for us to potentially combine projects, contributors, and effort. No pressure!

**Comment by aehrenthal** [comment]
Hey Drew,

Sorry for getting back to you just now - we were having a major release at my work, so my full attention was focused on that last week. Thank you very much for the offer to combine our projects, I think the work you did on swagger-to-ts is excellent! Unfortunately, I would have to decline your offer at this point. openapi-to-ts is my first contribution to the open-source community and I am personally quite keen on keeping it. However, I'd be more than happy to stay in touch and see if that might change in the future!

**Comment by drwpow** [comment]
Completely understand, and also I agree—you should keep this as your first contribution! That’s the beauty of open-source, too—getting to have control over the direction of where you think the project should go.

Likewise—would be happy to stay in touch, and also let me know if you’d like any contributions to this project, but completely within this scope and project goals. 🙂
